### ISSUE TITLE
collection.find_one query by ObjectId

### ISSUE THREAD

**Issue by aurickislam** [oatpp/oatpp-mongo#7]
How can I query by **"_id" : ObjectId**?. For example:
``` cpp
auto result =
    collection.find_one(createMongoDocument( // <-- Filter
      oatpp::Fields<oatpp::String>({
        {"_id", "ObjectID(\"5f3258cfbaaccedaa5dd2d96\")"}
      })
    ));
```

**Comment by lganzzzo** [comment]
Hello @aurickislam ,

Take a look at this issue - https://github.com/oatpp/oatpp-mongo/issues/6

You'll need that `objectIdFromString` method:

```cpp
auto result =
  collection.find_one(createMongoDocument( // <-- Filter
    oatpp::Fields({
      {"_id", objectIdFromString("5f3258cfbaaccedaa5dd2d96")}
    })
  ));
```

This is for now.
Later, ObjectId will have a from-string constructor.

**Comment by aurickislam** [comment]
Thanks it worked. But needed to specify `oatpp::Fields` type to `oatpp::Fields<oatpp::Any>`

```cpp
auto result =
    collection.find_one(createMongoDocument( // <-- Filter
      oatpp::Fields<oatpp::Any>({
        {"_id", objectIdFromString("5f3258cfbaaccedaa5dd2d96")}
      })
    ));
```

**Comment by lganzzzo** [comment]
> Thanks it worked. But needed to specify oatpp::Fields type to oatpp::Fields<oatpp::Any>

Yes, you are correct.
Thanks for posting the correct answer!
