### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by clarkholdham** [oatpp/oatpp-mongo#8]
In file: oatpp-mongo/bson/Types.hpp

# Question

Hi there, we are using BODY_DTO(oatpp::Any, value) to capture raw json into our endpoints but having issues with quotes around JSON. We would like to use our own json formats and objects (not DTOs). Therefor we need to be able to retrieve raw json without being encapsulated in quotes. Is there a way to receive JSON in the body and push it into a string or another object type without wrapping the whole JSON object is quotes. For example we want to send:  {"user":"admin"} instead of "{"user":"admin"}".

**Comment by lganzzzo** [comment]
Hello @clarkholdham ,

You can receive body as string:

```cpp
  ENDPOINT("POST", "/", postBody, 
           BODY_STRING(String, body)) 
  {
    ...
  }
```

**Comment by clarkholdham** [comment]
Got it, thank you very much.
